version: '3.8'

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  playwright-service:
    image: mcr.microsoft.com/playwright:v1.40.0-jammy
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
    command: >
      sh -c "
        npx playwright install chromium &&
        node -e \"
          const http = require('http');
          const server = http.createServer(async (req, res) => {
            if (req.url === '/health') {
              res.writeHead(200);
              res.end('OK');
              return;
            }
            res.writeHead(200);
            res.end('Playwright service ready');
          });
          server.listen(3000, '0.0.0.0', () => {
            console.log('Playwright service listening on port 3000');
          });
        \"
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s

  # Firecrawl API only (no nginx)
  firecrawl:
    build:
      context: .
      dockerfile: Dockerfile.api  # Use original Dockerfile without nginx
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3002
      - HOST=0.0.0.0
      - NUM_WORKERS_PER_QUEUE=8
      - REDIS_HOST=redis
      - REDIS_URL=redis://redis:6379
      - REDIS_RATE_LIMIT_URL=redis://redis:6379
      - USE_DB_AUTHENTICATION=false
      - PLAYWRIGHT_MICROSERVICE_URL=http://playwright-service:3000
      - LOGGING_LEVEL=info
    depends_on:
      redis:
        condition: service_healthy
      playwright-service:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data

  # Separate nginx service
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./playground.html:/usr/share/nginx/html/index.html:ro
    depends_on:
      - firecrawl

  bull-dashboard:
    image: deadly0/bull-board:latest
    restart: unless-stopped
    ports:
      - "3333:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

volumes:
  redis_data:
